### ISSUE TITLE
currency db

### ISSUE THREAD

**Issue by dymanLPT** [dyman/LazyPortfolioTracker#10]
save data from 
http://stackoverflow.com/questions/3139879/how-do-i-get-currency-exchange-rates-via-an-api-such-as-google-finance

http://www.ecb.europa.eu/stats/eurofxref/eurofxref-daily.xml

http://www.ecb.europa.eu/stats/exchange/eurofxref/html/usd.xml
http://www.ecb.europa.eu/stats/exchange/eurofxref/html/huf.xml

https://github.com/hakanensari/fixer-io

https://www.playframework.com/documentation/2.4.4/ScalaAkka

http://alvinalexander.com/scala/how-to-load-xml-url-in-scala-rss-restful-contents
rate
    id
    currency_id
    date  
    rate

currency
    id
    name

"USD"
"JPY"
"BGN"
"CZK"
"DKK"
"GBP"
"HUF"
"PLN"
"RON"
"SEK"
"CHF"
"NOK"
"HRK"
"RUB"
"TRY"
"AUD"
"BRL"
"CAD"
"CNY"
"HKD"
"IDR"
"ILS"
"INR"
"KRW"
"MXN"
"MYR"
"NZD"
"PHP"
"SGD"
"THB"
"ZAR"

**Comment by dyman** [comment]
ha a db ures:
Init: https://www.ecb.europa.eu/stats/eurofxref/eurofxref-hist.xml
szinkronizacio az utolso 90 nappal
https://www.ecb.europa.eu/stats/eurofxref/eurofxref-hist-90d.xml

**Comment by dyman** [comment]
USD US dollar  
JPY Japanese yen  
BGN Bulgarian lev  
CZK Czech koruna  
DKK Danish krone  
GBP Pound sterling  
HUF Hungarian forint  
PLN Polish zloty  
RON Romanian leu  
SEK Swedish krona  
CHF Swiss franc  
NOK Norwegian krone  
HRK Croatian kuna  
RUB Russian rouble  
TRY Turkish lira  
AUD Australian dollar  
BRL Brazilian real  
CAD Canadian dollar  
CNY Chinese yuan renminb
HKD Hong Kong dollar  
IDR Indonesian rupiah  
ILS Israeli shekel  
INR Indian rupee  
KRW South Korean won  
MXN Mexican peso  
MYR Malaysian ringgit  
NZD New Zealand dollar  
PHP Philippine peso  
SGD Singapore dollar  
THB Thai baht  
ZAR South African rand  
ISK Icelandic krona
